"""Synthesize realistic test events for the notifications feature.

Creates one batch of clearly-synthetic ("[TEST]"-prefixed) events against a
*running deployment* through its real public/admin HTTP API — contact
messages, hosting interest, a volunteer application, a community upload, and
(optionally) a new member — so rate limits, validation, emails, and the
notification badges/digest are all exercised end-to-end, exactly as a real
visitor would trigger them.

Usage:
    poetry run python scripts/synthesize_test_events.py \\
        --api-url https://<develop-backend> \\
        --chapter sf --count 2 --contact-email you@x.co [--cleanup]

Admin credentials come from --admin-email/--admin-password, or the
SYNTH_ADMIN_EMAIL / SYNTH_ADMIN_PASSWORD environment variables.

WARNING: contact messages created by this script are forwarded by email to
the target chapter's real chapter leads (or superadmins, if the chapter has
none) immediately. Run this against the develop deployment, not production,
unless that is genuinely what you intend.
"""
from __future__ import annotations

import argparse
import asyncio
import os
import struct
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone

import httpx

WARNING = (
    "WARNING: contact messages created by this script are forwarded by "
    "email to the target chapter's real chapter leads (or superadmins) "
    "immediately. Run this against the develop deployment, not production, "
    "unless that is what you intend.\n"
)

# Where each category shows up in the admin UI, for the closing summary.
ADMIN_PAGES = {
    "contact_messages": "/contact-messages",
    "hosting_interest": "/hosting-interest",
    "volunteer_applications": "/volunteer-applications",
    "community_uploads": "/community-uploads",
    "new_members": "/people (Team)",
}


# ── Payload builders (validated in tests against the real Pydantic models) ──


def make_wav_stub() -> bytes:
    """Return a minimal-but-valid 1-second silent mono WAV file.

    Starts with the RIFF/WAVE magic bytes `app/api/community.py`'s
    `_is_audio` checks for, and carries real (silent) PCM sample data past
    the 44-byte header so it reads as genuine audio rather than a bare
    header.
    """
    sample_rate = 8000
    num_channels = 1
    bits_per_sample = 8
    frame_data = bytes([128]) * sample_rate  # 1s; 128 == silence for 8-bit unsigned PCM
    data_size = len(frame_data)
    byte_rate = sample_rate * num_channels * bits_per_sample // 8
    block_align = num_channels * bits_per_sample // 8
    header = (
        b"RIFF"
        + struct.pack("<I", 36 + data_size)
        + b"WAVE"
        + b"fmt "
        + struct.pack("<I", 16)
        + struct.pack(
            "<HHIIHH", 1, num_channels, sample_rate, byte_rate, block_align, bits_per_sample
        )
        + b"data"
        + struct.pack("<I", data_size)
    )
    return header + frame_data


def run_id() -> str:
    """Microsecond-precision timestamp suffix used to keep synthetic records
    (fake member username/email, fallback volunteer role slug) unique across
    runs."""
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")


def contact_payload(i: int, contact_email: str) -> dict:
    """POST /chapters/{code}/contact body — matches app.schemas.contact.ContactRequest."""
    return {
        "name": f"[TEST] Visitor {i}",
        "email": contact_email,
        "message": (
            f"[TEST] Synthetic contact message #{i} generated by "
            "synthesize_test_events.py to exercise notification badges. "
            "Safe to ignore or delete."
        ),
        "website": None,  # honeypot — must stay empty
    }


def hosting_payloads(chapter_name: str, contact_email: str) -> list[dict]:
    """POST /hosting-interest bodies — matches
    app.api.hosting_interest.HostingInterestCreate. One host_existing for
    the given chapter, one start_chapter."""
    return [
        {
            "name": "[TEST] Prospective Host",
            "email": contact_email,
            "city": "Testville",
            "interest_type": "host_existing",
            "existing_chapter": chapter_name,
            "message": (
                "[TEST] Synthetic host_existing hosting interest generated "
                "by synthesize_test_events.py."
            ),
        },
        {
            "name": "[TEST] Chapter Founder",
            "email": contact_email,
            "city": "New Testopolis",
            "interest_type": "start_chapter",
            "message": (
                "[TEST] Synthetic start_chapter hosting interest generated "
                "by synthesize_test_events.py."
            ),
        },
    ]


def volunteer_payload(contact_email: str) -> dict:
    """POST /volunteer-roles/{slug}/apply body — matches
    app.api.volunteer.VolunteerApplyRequest."""
    return {
        "name": "[TEST] Volunteer Applicant",
        "email": contact_email,
        "city": "Testville",
        "why_interested": (
            "[TEST] Synthetic application generated by "
            "synthesize_test_events.py to exercise the volunteer badge."
        ),
        "relevant_experience": "[TEST] N/A — synthetic data.",
        "availability": "[TEST] Weekday evenings (synthetic).",
        "how_heard": "[TEST] synthesize_test_events.py",
    }


# ── Result ───────────────────────────────────────────────────────────────────


@dataclass
class SynthesisResult:
    """Everything created by one `synthesize()` run, for printing and for
    `cleanup()` to act on."""

    chapter_id: str
    chapter_code: str
    chapter_name: str
    admin_token: str
    contact_message_ids: list[str] = field(default_factory=list)
    hosting_interest_ids: list[str] = field(default_factory=list)
    volunteer_role_id: str = ""
    volunteer_role_slug: str = ""
    volunteer_role_created: bool = False
    volunteer_application_id: str = ""
    community_upload_id: str = ""
    invite_id: str | None = None
    member: dict | None = None

    def admin_headers(self) -> dict:
        return {"Authorization": f"Bearer {self.admin_token}"}


# ── Internal helpers ─────────────────────────────────────────────────────────


async def _admin_login(client: httpx.AsyncClient, email: str, password: str) -> str:
    r = await client.post("/auth/login", json={"identifier": email, "password": password})
    r.raise_for_status()
    return r.json()["access_token"]


async def _ensure_volunteer_role(
    client: httpx.AsyncClient, headers: dict, chapter: dict
) -> tuple[dict, bool]:
    """Return (role, created) — an active volunteer role scoped to this
    chapter to apply against, creating a [TEST] one via the admin API if
    none exists yet."""
    r = await client.get("/volunteer-roles", params={"chapter_code": chapter["code"]})
    r.raise_for_status()
    roles = r.json()
    if roles:
        return roles[0], False
    print(
        f"  No active volunteer role for '{chapter['name']}' — creating "
        "a [TEST] role via the admin API"
    )
    payload = {
        "title": "[TEST] Synthetic Volunteer Role",
        "slug": f"test-synth-role-{run_id()}",
        "description": (
            "[TEST] Created by synthesize_test_events.py to exercise the "
            "volunteer-application badge. Safe to delete."
        ),
        "chapter_id": chapter["id"],
        "is_active": True,
        "display_order": 999,
    }
    r = await client.post("/admin/volunteer-roles", json=payload, headers=headers)
    r.raise_for_status()
    return r.json(), True


async def _find_recent_contact_ids(
    client: httpx.AsyncClient,
    headers: dict,
    chapter_id: str,
    contact_email: str,
    n: int,
) -> list[str]:
    """The public contact endpoint returns no id (just {"detail": ...}), so
    look the created rows back up via the admin list — matched by chapter +
    sender email + still-`new` status, newest first, so a previous
    uncleaned-up run's leftovers never crowd out this run's records."""
    r = await client.get("/admin/contact-messages", headers=headers)
    r.raise_for_status()
    matches = [
        m
        for m in r.json()
        if m["chapter_id"] == chapter_id
        and m["email"] == contact_email
        and m["status"] == "new"
    ]
    matches.sort(key=lambda m: m["created_at"], reverse=True)
    return [m["id"] for m in matches[:n]]


# ── Main flow ────────────────────────────────────────────────────────────────


async def synthesize(
    client: httpx.AsyncClient,
    chapter_code: str,
    count: int,
    contact_email: str,
    admin_email: str,
    admin_password: str,
    include_member: bool = True,
) -> SynthesisResult:
    """Create one batch of [TEST]-prefixed synthetic events for `chapter_code`
    through the real public/admin HTTP API and print a summary of what was
    created and where to see it.
    """
    print(WARNING)
    rid = run_id()

    r = await client.get(f"/chapters/{chapter_code}")
    r.raise_for_status()
    chapter = r.json()
    print(f"Chapter resolved: {chapter['name']} ({chapter['code']})")

    # Admin auth up front: needed to create a fallback volunteer role (if
    # none is active yet), to create the member invite, and to look up the
    # ids of records the public endpoints below don't return (contact
    # messages) so --cleanup has something to act on.
    admin_token = await _admin_login(client, admin_email, admin_password)
    headers = {"Authorization": f"Bearer {admin_token}"}
    print(f"Authenticated as admin: {admin_email}")

    # 1. Contact messages
    for i in range(1, count + 1):
        r = await client.post(
            f"/chapters/{chapter_code}/contact", json=contact_payload(i, contact_email)
        )
        r.raise_for_status()
    contact_ids = await _find_recent_contact_ids(
        client, headers, chapter["id"], contact_email, count
    )
    print(f"Created {count} contact message(s) -> see {ADMIN_PAGES['contact_messages']}")

    # 2. Hosting interest (host_existing + start_chapter)
    hosting_ids = []
    for payload in hosting_payloads(chapter["name"], contact_email):
        r = await client.post("/hosting-interest", json=payload)
        r.raise_for_status()
        hosting_ids.append(r.json()["id"])
    print(
        "Created 2 hosting-interest submissions (host_existing + start_chapter) "
        f"-> see {ADMIN_PAGES['hosting_interest']}"
    )

    # 3. Volunteer application
    role, role_created = await _ensure_volunteer_role(client, headers, chapter)
    r = await client.post(
        f"/volunteer-roles/{role['slug']}/apply", json=volunteer_payload(contact_email)
    )
    r.raise_for_status()
    application = r.json()
    print(
        f"Applied to volunteer role '{role['title']}' -> see "
        f"{ADMIN_PAGES['volunteer_applications']}"
    )

    # 4. Community upload
    files = {"file": ("synth-test.wav", make_wav_stub(), "audio/wav")}
    data = {
        "name": "[TEST] Community Uploader",
        "email": contact_email,
        "city": chapter["name"],
        "topic_text": "[TEST] synthetic topic",
    }
    r = await client.post("/community/upload", data=data, files=files)
    r.raise_for_status()
    upload = r.json()
    print(f"Uploaded a community recording -> see {ADMIN_PAGES['community_uploads']}")

    # 5. New member (optional)
    invite_id = None
    member = None
    if include_member:
        r = await client.post(
            "/admin/invites",
            json={"chapter_id": chapter["id"], "role": "host", "max_uses": 1},
            headers=headers,
        )
        r.raise_for_status()
        invite = r.json()
        invite_id = invite["id"]
        username = f"[TEST]_member_{rid}"
        member_email = f"test-member-{rid}@aisalon-synth.test"
        password = f"TestSynth{rid}Aa1!"
        r = await client.post(
            "/auth/register",
            json={
                "invite_token": invite["token"],
                "username": username,
                "email": member_email,
                "password": password,
            },
        )
        r.raise_for_status()
        member_token = r.json()["access_token"]
        r = await client.get(
            "/admin/me", headers={"Authorization": f"Bearer {member_token}"}
        )
        r.raise_for_status()
        member = r.json()
        print(
            f"Registered new member '{username}' <{member_email}> -> see "
            f"{ADMIN_PAGES['new_members']}"
        )
    else:
        print("Skipped new-member creation (--no-include-member)")

    print(
        "\nDone. To see a digest email right now, as a superadmin call:\n"
        '  POST /admin/digests/run-test  {"window_days": 7, "only_me": true}\n'
        "(bypasses the weekly run-guard and, by default, sends only to the caller)."
    )

    return SynthesisResult(
        chapter_id=chapter["id"],
        chapter_code=chapter["code"],
        chapter_name=chapter["name"],
        admin_token=admin_token,
        contact_message_ids=contact_ids,
        hosting_interest_ids=hosting_ids,
        volunteer_role_id=role["id"],
        volunteer_role_slug=role["slug"],
        volunteer_role_created=role_created,
        volunteer_application_id=application["id"],
        community_upload_id=upload["id"],
        invite_id=invite_id,
        member=member,
    )


# ── Cleanup ──────────────────────────────────────────────────────────────────


async def _safe_patch(
    client: httpx.AsyncClient, headers: dict, path: str, body: dict, label: str
) -> None:
    try:
        r = await client.patch(path, json=body, headers=headers)
        r.raise_for_status()
        print(f"  Marked {label} as {body.get('status')}")
    except httpx.HTTPStatusError as exc:
        print(f"  Could not update {label} via {path} ({exc}). Please clean up manually.")


async def cleanup(client: httpx.AsyncClient, result: SynthesisResult) -> None:
    """Mark everything this run created as handled/reviewed via the admin
    endpoints that already exist for it, and deactivate the synthetic
    volunteer role (only if this run created one), invite, and member user.

    Contact messages and hosting interest have no delete endpoint (by
    design — they're marked handled, not removed), so cleanup for those is
    always the handled-PATCH, never a delete.
    """
    print("\n=== Cleanup ===")
    headers = result.admin_headers()

    for cid in result.contact_message_ids:
        await _safe_patch(
            client, headers, f"/admin/contact-messages/{cid}", {"status": "handled"},
            f"contact message {cid}",
        )
    for hid in result.hosting_interest_ids:
        await _safe_patch(
            client, headers, f"/admin/hosting-interest/{hid}", {"status": "handled"},
            f"hosting interest {hid}",
        )
    await _safe_patch(
        client,
        headers,
        f"/admin/volunteer-applications/{result.volunteer_application_id}",
        {"status": "reviewed"},
        f"volunteer application {result.volunteer_application_id}",
    )
    await _safe_patch(
        client,
        headers,
        f"/admin/community-uploads/{result.community_upload_id}",
        {"status": "reviewed"},
        f"community upload {result.community_upload_id}",
    )

    if result.volunteer_role_created:
        try:
            r = await client.delete(
                f"/admin/volunteer-roles/{result.volunteer_role_id}", headers=headers
            )
            r.raise_for_status()
            print(f"  Deactivated synthetic volunteer role {result.volunteer_role_id}")
        except httpx.HTTPStatusError as exc:
            print(
                f"  Could not deactivate volunteer role {result.volunteer_role_id} "
                f"({exc}). Please deactivate it manually."
            )

    if result.invite_id:
        try:
            r = await client.delete(f"/admin/invites/{result.invite_id}", headers=headers)
            r.raise_for_status()
            print(f"  Deactivated invite {result.invite_id}")
        except httpx.HTTPStatusError as exc:
            print(
                f"  Could not deactivate invite {result.invite_id} ({exc}). "
                "Please deactivate it manually."
            )

    if result.member:
        try:
            r = await client.patch(
                f"/admin/users/{result.member['id']}",
                json={"is_active": False},
                headers=headers,
            )
            r.raise_for_status()
            print(f"  Deactivated test member {result.member['email']}")
        except httpx.HTTPStatusError as exc:
            print(
                f"  Could not deactivate user {result.member['id']} via the admin "
                f"API ({exc}). Manually deactivate or delete this account: "
                f"{result.member['email']}"
            )


# ── CLI ──────────────────────────────────────────────────────────────────────


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--api-url",
        required=True,
        help="Base URL of the running backend, e.g. https://<develop-backend>",
    )
    p.add_argument("--chapter", default="sf", help="Chapter code to target (default: sf)")
    p.add_argument(
        "--count", type=int, default=2, help="Number of contact messages to create (default: 2)"
    )
    p.add_argument(
        "--contact-email",
        required=True,
        help="Email address used as the fake visitor for all synthetic submissions",
    )
    p.add_argument(
        "--admin-email",
        default=os.environ.get("SYNTH_ADMIN_EMAIL"),
        help="Superadmin/chapter-lead email (default: $SYNTH_ADMIN_EMAIL)",
    )
    p.add_argument(
        "--admin-password",
        default=os.environ.get("SYNTH_ADMIN_PASSWORD"),
        help="Password for --admin-email (default: $SYNTH_ADMIN_PASSWORD)",
    )
    p.add_argument(
        "--include-member",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Also register a synthetic new member via an invite (default: on)",
    )
    p.add_argument(
        "--cleanup",
        action="store_true",
        help="After creating events, mark/deactivate everything this run created",
    )
    return p


async def _run(args: argparse.Namespace) -> int:
    if not args.admin_email or not args.admin_password:
        print(
            "ERROR: admin credentials required — pass --admin-email/--admin-password "
            "or set SYNTH_ADMIN_EMAIL/SYNTH_ADMIN_PASSWORD.",
            file=sys.stderr,
        )
        return 1

    async with httpx.AsyncClient(base_url=args.api_url, timeout=30.0) as client:
        try:
            result = await synthesize(
                client,
                chapter_code=args.chapter,
                count=args.count,
                contact_email=args.contact_email,
                admin_email=args.admin_email,
                admin_password=args.admin_password,
                include_member=args.include_member,
            )
        except httpx.HTTPStatusError as exc:
            print(
                f"ERROR: {exc.request.method} {exc.request.url} -> "
                f"{exc.response.status_code}: {exc.response.text}",
                file=sys.stderr,
            )
            return 1

        if args.cleanup:
            await cleanup(client, result)

    return 0


def main() -> int:
    args = build_arg_parser().parse_args()
    return asyncio.run(_run(args))


if __name__ == "__main__":
    raise SystemExit(main())
