from abc import ABC, abstractmethod


class BaseProcessor(ABC):
    @abstractmethod
    async def process(self, storage_key: str, chapter_id: str) -> dict:
        """Process an uploaded audio file; return article data dict."""
        ...


class StubProcessor(BaseProcessor):
    """Placeholder until SocraticAI is wired in."""

    async def process(self, storage_key: str, chapter_id: str) -> dict:
        return {
            "title": "Stub Article",
            "content_md": "# Stub Article\n\nThis is a placeholder generated by StubProcessor.",
        }
