"""add city topic_text to community_uploads

Revision ID: c6a309d66dc5
Revises: 5132f69258e4
Create Date: 2026-04-18 15:15:28.212582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a309d66dc5'
down_revision: Union[str, Sequence[str], None] = '5132f69258e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_uploads', sa.Column('topic_text', sa.String(length=256), nullable=True))
    op.add_column('community_uploads', sa.Column('city', sa.String(length=256), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_uploads', 'city')
    op.drop_column('community_uploads', 'topic_text')
    # ### end Alembic commands ###
